baseURL: "/"
title: "Qim Center"
summaryLength: 20

buildFuture: true
enableRobotsTXT: true

# Enable raw HTML rendering in markdown
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block: [['\[', '\]'], ['$$', '$$']]
          inline: [['\(', '\)'], ['$', '$']]

# Set baseURL to the final public site URL before publishing.
# services:
#   googleAnalytics:
#     id: G-MEASUREMENT_ID
