main:
  - name: "About Us"
    url: "/about"
    weight: 1

  - name: "What we do"
    url: "/portfolio"
    weight: 1

  - name: "Publications"
    url: "/publications"
    weight: 4

buttons:
  - name: "Contact Us"
    url: "/contact"
    weight: 4

footer:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "About Us"
    url: "/about"
    weight: 2

  - name: "Contact Us"
    url: "/contact"
    weight: 5
