main:
  - name: "About Us"
    identifier: about-us
    url: "/about"
    weight: 1

  - name: "Qim Center"
    parent: about-us
    url: "/about"
    weight: 1

  - name: "Publications"
    parent: about-us
    url: "/publications"
    weight: 2

  - name: "Showcases"
    url: "/showcases"
    weight: 2

  - name: "Resources"
    identifier: resources
    url: "/tools"
    weight: 3

  - name: "Software Tools"
    parent: resources
    url: "/tools"
    weight: 1

  - name: "Qim Platform"
    parent: resources
    url: "https://platform.qim.dk"
    weight: 2

  - name: "Volume Explorer"
    parent: resources
    url: "https://viz.qim.dk"
    weight: 3

  - name: "Data Repository"
    parent: resources
    url: "https://data-repository.qim.dk"
    weight: 4

  - name: "Research Support"
    url: "/support"
    weight: 4

  - name: "Events"
    url: "/events"
    weight: 5

buttons:
  - name: "Contact Us"
    url: "/contact"
    weight: 4

footer:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "About Us"
    url: "/about"
    weight: 2

  - name: "Contact Us"
    url: "/contact"
    weight: 5