main:
  - name: "About Us"
    url: "/about"
    weight: 1

  - name: "Showcases"
    url: "/showcases"
    weight: 2

  - name: "Research Support"
    url: "/support"
    weight: 3

  - name: "Events"
    url: "/events"
    weight: 4

  - name: "Publications"
    url: "/publications"
    weight: 5

buttons:
  - name: "Contact Us"
    url: "/contact"
    weight: 4

footer:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "About Us"
    url: "/about"
    weight: 2

  - name: "Contact Us"
    url: "/contact"
    weight: 5
