title: "Qim Center"
description: "Algorithms for quantitative image analysis."
images: 
  - "images/home/hero/qim-logo.png"

logo: "images/shared/qim-logo_standard-transparent-background.png"
logoHover: "images/shared/qim-logo_gradient-transparent-background.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

contact:
  - "info@qim.dk"
  - "207.555.0119"

social:
  dribbble: "#"
  instagram: "#"
  facebook: "#"
  twitter: "#"

copyright: "© 2026 Qim Center. All rights reserved."

colors:
  primary: "#FC7323"
  secondary: "#E63F47"